### ISSUE TITLE
AssetBundlePathResolver.GetBundleSourceFile路径返回错误

### ISSUE THREAD

**Issue by 3wz** [tangzx/ABSystem#10]
我写了个同步加载方法, 然后在IOS下ab加载不出来, 看了下路径才发现, 本来有forWWW做判断, 但是最后一个宏else没有这个判断直接返回file://开头的路径了, 坑啊~~ 劳烦您改下吧~

**Comment by tangzx** [comment]
已更新，这里是我疏忽了，之前可能是写漏了...
