### ISSUE TITLE
如何加快做版本的速度？

### ISSUE THREAD

**Issue by cywater2000** [tangzx/ABSystem#11]
你好，请教个实际问题：如何加快做版本的速度？

以我们的游戏为例，如果不用AB模式，做版本大概10分钟左右。(即用Resources.Load)
如果要用AB包，第一次做版本需要大概2个小时。后续就算增量打包AB包也要30分钟左右。这个时间对于正常的项目迭代实在是无法忍受。

打包AB时间主要消耗在2个方面：
一是分析需要打包的资源，LoadAsset资源慢，CollectDependencies更慢
二是打包本身慢BuildAssetBundle，特别是地图修改的话。如果开了压缩打包，时间还要增加

请问有没有什么优化建议？谢谢

**Comment by tangzx** [comment]
开发模式下不用打AB，发行包的话如果你们资源改动的很多，打AB时间长这是没办法的事，除非不使用AB，看项目需求了

**Comment by tangzx** [comment]
推荐使用CI系统（如Jenkins）定时自动打包，这样到真正需要发行时打AB的时间也不用那么长了

**Comment by cywater2000** [comment]
平时不测试AB，发版本的时候可能会有bug啊。有些时候，非AB下没问题，AB下可能就会有问题了。这是肯定会发生的。

**Comment by tangzx** [comment]
是的，所以要经常打Ab真机测试，这是必须的。留到发版本那一天来测肯定要加班了...

**Comment by cywater2000** [comment]
应该不是经常测试，应该是每天测试吧？这就回到加快打包速度问题上来了。
另外，请问你们是所有资源都打AB包吗？我是打算所有地图和Resources下的资源都变成AB包。

**Comment by tangzx** [comment]
是的，我们也全部打AB

**Comment by cywater2000** [comment]
那目前你们多长时间做一次AB的版本

**Comment by tangzx** [comment]
现在稳定了，基本是在版本前一天打好

**Comment by cywater2000** [comment]
有没有出现过节点当天连续打版本测试的情况？如何解决？

**Comment by cywater2000** [comment]
另外请问你用的是Unity5的64位版本吧？Unity4没有64位版本，在分析的时候很容易内存很容易崩溃

**Comment by tangzx** [comment]
连续打版本有什么问题？交给测试去打

**Comment by tangzx** [comment]
U4项目里资源过多是有可能内存不足崩溃

**Comment by cywater2000** [comment]
连续打版本的时间问题，有没有实际遇到过，感觉迭代速度慢？

**Comment by tangzx** [comment]
慢是什么意思？我们第一个版本因为要更新AB所以时间不定，后面的就快了，4，5分钟完成

**Comment by cywater2000** [comment]
分析本身就要4，5分钟吧～如果真正要更新就更慢了。难道因为是U5 64位版本的原因？

**Comment by tangzx** [comment]
U5肯定比U4要好些，另外机器也配置好些吧，用上SSD

**Comment by cywater2000** [comment]
原来如此，看来要考虑ssd了。谢谢

**Comment by tangzx** [comment]
不客气
