### ISSUE TITLE
AssetBundleInfo Dispose方法资源没有被释放的问题

### ISSUE THREAD

**Issue by huangkumao** [tangzx/ABSystem#15]
我修改了下 

        public virtual void Dispose()
        {
            UnloadBundle(true);
            ......
         }

        void UnloadBundle(bool unload = false)
        {
            if (bundle != null)
            {
                if (AssetBundleManager.enableLog)
                    Debug.Log("Unload : " + data.compositeType + " >> " + data.debugName);

                bundle.Unload(unload);
            }
            bundle = null;
        }

这样释放的时候 相当于调用了 AssetBundle.Unload(true). 我测试了一下Profiler里面可以正常把贴图给释放掉了.

不知道我理解的对不对

**Comment by huangkumao** [comment]
如果不这样改的话 需要自己调用一次 Resources.UnloadUnusedAssets(); 才会释放掉

**Comment by huangkumao** [comment]
另外我发现一个问题 Test.cs
GameObject go = Instantiate(a.mainObject) as GameObject;//a.Instantiate();
如果 GameObject go = Instantiate(a.mainObject) as GameObject; 这种写法好像有问题.
应该使用 后面的 a.Instantiate();
我不清楚是不是我使用的方法有问题.

**Comment by tangzx** [comment]
1.首先Dispose是AssetBundleManager调用的，不要手动调用，AssetBundle.Unload(true)比较不安全，它会把所有的实例也销毁了，即使你正在使用的。
2.是的，a.mainObject尽量不要使用，使用a.Instantiate()， 这样ABSystem会对AB的引用自动管理，自动帮你卸载不用的AB

**Comment by tangzx** [comment]
没有释放的问题可能你有正在使用的ab资源的实例吧，实在不行你手动调用Resources.UnloadUnusedAssets()也是可取的，但是建议不要AssetBundle.Unload(true)，除非你能很明确外部已经没有任何引用它的资源存在，否则是不安全的

**Comment by huangkumao** [comment]
好的 我在测试一下 我感觉现在的框架AssetBundle.Unload(true)其实没有问题 一个资源被多个引用 调到AssetBundle.Unload(true)的地方只有Dispose 这个是引用计数为0的情况下才会调用的.  暂时感觉没问题提. 我会在测试测试.

感谢
