### ISSUE TITLE
想问下，为什么5.x就不用做meta比对了呢

### ISSUE THREAD

**Issue by justinlm** [tangzx/ABSystem#18]
举个例子：Shader，假设添加了shader的defaultTextures。5.x中也只是改变shader的meta文件而已。这样子是不是有点问题呢。

**Comment by tangzx** [comment]
unity5 会自动处理这些

**Comment by justinlm** [comment]
额，对哦。shader的mata变了以后，它自己没变，但是它的依赖跟着变了。谢了。
