### ISSUE TITLE
有个问题，这样粒度是不是太小了

### ISSUE THREAD

**Issue by li5414** [tangzx/ABSystem#2]
比如一个角色，可能会用到n个材质，n张图，n个mesh，这样如果一个个加载太碎了，这样不是好事吧

**Comment by tangzx** [comment]
碎不碎看资源的引用关系，如果一个素材被一个以上的其它素材引用，那么它就被单独打包。
一个简单的例子：
情况一：A引用X，且X只被A用了，那么打包A时，A和X是打在一起的不会拆
情况二：A引用X，B也引用X，那么在打A和B时，先将X单独打包，再打A和B。这样的目的是保证每一个素材只会被打一次，内存中不会重复
