### ISSUE TITLE
同步加载~

### ISSUE THREAD

**Issue by talentJian** [tangzx/ABSystem#22]
有什么方法可以实现同步加载AB吗？

**Comment by ww386362087** [comment]
I want to know ....

**Comment by tangzx** [comment]
#5

**Comment by ww386362087** [comment]
我看龙之谷的里面用到了你的ABSystem  他实现了同步加载与异步加载




发自网易邮箱大师


在2018年01月30日 19:02，阿唐<notifications@github.com> 写道：

#5

**Comment by tangzx** [comment]
可以是可以，自己魔改一下。同步异步只能用一种
