### ISSUE TITLE
在Unity Editor5.6.4下，切换到Android平台，材质Shader为Unlit/Texture时，通过AB加载模型显示紫色

### ISSUE THREAD

**Issue by motan2008** [tangzx/ABSystem#25]
在Unity Editor5.6.4下，切换到Android平台，材质Shader为Unlit/Texture时，通过AB加载模型显示紫色.

材质Shader为Legacy Shaders/Diffuse时，通过AB加载模型显示正常呢。
Demo场景可复现。

**Comment by tangzx** [comment]
这不是BUG，手机平台的shader已经编译在ab里，在PC上自然用不了而显示为紫色。放到手机上能正常即可

**Comment by motan2008** [comment]
嗯 在手机上能正常显示
