### ISSUE TITLE
关于AssetBundleDataReader的疑问

### ISSUE THREAD

**Issue by Scofield-Logique** [tangzx/ABSystem#27]
AssetBundleDataReader中有个字段shortName2FullName。我疑惑的是这个dictionary的key-shortname，可能不具有唯一性。这种时候，  方法public string GetPathByShortName(string shortName)真的能够成立么？还是说应该在取名字的时候就人为地确定唯一性？

**Comment by tangzx** [comment]
是的，有可能不唯一。这个... 是个历史遗留问题，不建议使用
