### ISSUE TITLE
关于Builtin资源

### ISSUE THREAD

**Issue by cywater2000** [tangzx/ABSystem#3]
你好，在Unity 4.x 下面，Builtin资源并没有标记为AssetType.Builtin
但是在BuildExportTree，needSelfExport，GetHash的时候，是把Builtin特殊处理过了。但实际上永远不会执行？请问是bug还是有意为之？

另外，Builtin资源到底应该独立打包，还是随使用者一起打包？根据MobileAssetBundleLoader下有一个专门的LoadFromBuiltin，是否说明Builtin资源也应该独立打包单独加载？

谢谢

**Comment by tangzx** [comment]
Unity 4.x的很久没去维护了，本人一直在U5上工作，等有空我去看看怎么回事~

**Comment by tangzx** [comment]
AssetType.Builtin 这个貌似没什么用了，遗留的东西，刚开始的本意是指Unity内置资源，如一些shader。
关于LoadFromBuiltin，这个属于命名问题，让人产生了误解，其实它和AssetType.Builtin无关 -_-||，它指的是从安装包里加载ab，最新的代码已经改了名字叫 LoadFromPackage，与之相对应的 LoadFromFile改为LoadFromCachedFile...

**Comment by cywater2000** [comment]
那对于4.6这个系统，Unity内置资源需要特殊处理吗？还是说不用特殊处理？也是按照普通资源方式打包？只是打包的时候需要单独提取出来呢

我看对于5.0以上，你是特殊排除了内置资源的。4.x正好相反啊？

**Comment by tangzx** [comment]
不需要， 直接打包直接用就可以了

**Comment by cywater2000** [comment]
提取 resource.builtin 不需要了？

**Comment by tangzx** [comment]
是的，如果你发现什么问题可以通知我
