### ISSUE TITLE
唐哥，问个问题，增量打包是否有必要？

### ISSUE THREAD

**Issue by youxibuhaowana** [tangzx/ABSystem#31]
唐哥，看完你的ABSystem，但并未发现有增量打包的使用。
在AssetTarget类中有_isFileChanged标识该文件是否被修改, 但是该标志位并未被真正的使用到。
我们游戏项目中，初次打过一次ab后，以后每次新增资源打ab的速度都很快，仿佛unity内部做了增量打ab。
所以想问下 增量打ab是否有必要?

**Comment by tangzx** [comment]
嗯，这是遗留的，是为之前的4.X做的，现在没作用了。

**Comment by youxibuhaowana** [comment]
嗯，谢谢，看完你的代码，学到很多。
