### ISSUE TITLE
关于资源自动卸载

### ISSUE THREAD

**Issue by 435886030** [tangzx/ABSystem#32]
你好，我有个疑问：
首先，AssetBundleInfo.Instantiate()方式创建的go Instance能够由ABSystem去维护引用计数。

问题1:
1.对于不实例化直接使用的资源，则会直接访问mainObject，ABSystem对此无感知，有什么办法将此类型资源也管理起来么

2.目前AssetBundleInfo.UnloadBundle调用的是bundle.Unload(false)，只能卸载掉Bundle内存，对于资源类型（Texture等）并不能卸载掉，只能通过Resources.UnloadUnuseAsset来卸载（仍然会造成卡顿）。
如此一来，是否ABSystem直接调用Unload(true)更加有效呢？但需要考虑下直接引用mainObject如何管理引用

**Comment by tangzx** [comment]
1. 看主页示例代码
```c#
manager.Load("Assets.my_txture.png", (a) =>
{
    	Texture tex = a.Require(this); //自动管理：当this被Destroy时，AB会被释放回收
});
```
不要使用 mainObject 直接操作，这样是无法管理的， 用Require

2. `Unload(true)` 是比较危险使用方式，不建议使用。你可以在某个合适的时间比如切场景黑屏的时候Resources.UnloadUnuseAsset

**Comment by 435886030** [comment]
Texture tex = a.Require(this) ，这个将一个对象弱引用存到Bundle的references列表里了，但如果当上层逻辑再进行引用传递（Insatnce2.tex2 = tex;）那么虽然this被Destroy后 -> bundle卸载了，但资源已泄漏了。后续再加载"Assets.my_txture.png"，内存中就会存在两份，不过这种貌似没什么好办法。

**Comment by 435886030** [comment]
目前Unity Unload(false)后，资源和Bundle就断链了，所以我倾向于暴力Unload(true)，这样可以防止资源重复多份。但对于不Instantiate直接使用的Texture等资源，倾向于直接不卸载。谢谢唐哥

**Comment by tangzx** [comment]
是的，没想到有特别好的方法了，使用规范上多加注意吧
