### ISSUE TITLE
关于打Bundle的粒度

### ISSUE THREAD

**Issue by 435886030** [tangzx/ABSystem#33]
看到AssetTarget和其它代码中，进行打包的时候是考虑一个资源一个bundle的，请教一下是有什么特殊的考虑呢，为何不将一组资源打到一个bundle里？

拆到逐资源打bundle ，如果资源量大，bundle的额外内存开销是否也不小呢？

**Comment by MorningSirGitHub** [comment]
请问是否发生了你说的问题呢
