### ISSUE TITLE
资源没有变化的情况下，打包assetsBundle文件有变化

### ISSUE THREAD

**Issue by weiboooooy** [tangzx/ABSystem#35]
您好 ，在资源没有变化的情况下，打包assetsBundle文件有时会有变化。 我更新ab文件使用的是ab文件的md5码， 没有变化的情况下这个文件打包会变的话每次都要更新。

比如ab.manifest前后打包 ：

第一次 ：
Dependencies:
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/095634d3c9550412ebec2b25e678df86c613b298.ab
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/1e6903d1a595c4b6c711f0b087b53ad06a51caac.ab
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/d40908563ef95f57daaa40a5259d4aa7c238b0d2.ab
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/5058d1b4d2eaefcd6cae4f51fc4079eb92ac38c5.ab

第二次：
Dependencies:
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/1e6903d1a595c4b6c711f0b087b53ad06a51caac.ab
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/095634d3c9550412ebec2b25e678df86c613b298.ab
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/d40908563ef95f57daaa40a5259d4aa7c238b0d2.ab
- /Users/mac/Documents/toLua_gameHall/Assets/StreamingAssets/AssetBundles/5058d1b4d2eaefcd6cae4f51fc4079eb92ac38c5.ab

第一条和第二条的顺序变了

**Comment by weiboooooy** [comment]
这应该是我把上一次生成的ab文件删掉了，如果不删掉文件通过代码中的对比是没有从新生成的 ， 但是这样的话 如果换一个电脑打包 ，可能需要把ab包也同步过去吧。

**Comment by tangzx** [comment]
看起来是一样的吧，只是顺序变了
