### ISSUE TITLE
关于mainAsset导致的卡顿问题

### ISSUE THREAD

**Issue by 435886030** [tangzx/ABSystem#36]
Hi，唐哥，在我们调用AssetBundle.mainAsset取出mainAsset时，它的get方法会阻塞地去Load mainAsset
所以其实我们应该异步去LoadAssetAsync，以达到完全异步的目的吧？

**Comment by tangzx** [comment]
可能只会好一些吧，UNITY目前做不到完全异步。在获取asset时可能要初始化一些数据仍然是在主线程里执行的。你可以把一些耗时的操作分帧处理，或者预加载、预初始化

**Comment by 435886030** [comment]
了解了，多谢
