### ISSUE TITLE
关于压缩和非压缩打包的问题

### ISSUE THREAD

**Issue by cywater2000** [tangzx/ABSystem#4]
你好，为了使用 CreateFromFile，此系统采用的是非压缩打包。先不讨论自己压缩，网络下载完成再解压缩的问题，因为都可以写代码解决。(如果直接使用LoadFromCacheOrDownload可以避免上述问题)

但有一个问题，目前来看好像无法解决：初始包的大小。因为我们初始包会打完整包，放到StreamingAssets下。这个文件夹在真机上是只读的。

所以我们的项目还是采用LoadFromCacheOrDownload，压缩打包。

请问作者是怎么考虑这个问题的？

谢谢

**Comment by tangzx** [comment]
这个问题我也在纠结啊
在IOS上 LoadFromCacheOrDownload 第一次没有 CreateFromFile快，而且会产生一个解压的副本，占用手机内存会多一些
在Android上可以试试，因为Android上CreateFromFile不好使
如果有好的方案请告之，谢谢

**Comment by cywater2000** [comment]
Android可以用CreateFromFile啊。关于LoadFromCacheOrDownload第一次解压缩的问题，我想到的解决方法就是在游戏第一次运行时，先全部调用LoadFromCacheOrDownload一次解压缩，只不过url是本地文件

**Comment by tangzx** [comment]
哦哦，我说错了，我的意思是在iOS可以直接从StreamingAssets里CreateFromFile，而Android就得缓存一份到外部再CreateFromFile，（虽然也可以直接CreateFromFile，但太慢，因为是从apk/zip中读取的）
第一次运行时解压一遍可以考虑，有的游戏的确这样做的:+1:

**Comment by cywater2000** [comment]
恩，没有最完美的解决方案。暂时先用压缩吧
