### ISSUE TITLE
LoadMetaHashIfNecessary 只在非unity5的版本中执行？ 这个是什么意思

### ISSUE THREAD

**Issue by jeenfang** [tangzx/ABSystem#43]
/// <summary>
        /// Texture
        /// AudioClip
        /// Mesh
        /// Model
        /// Shader
        /// 这些类型的Asset的一配置是放在.meta中的，所以要监视它们的变化
        /// 而在5x中系统会自己处理的，不用管啦
        /// </summary>
        void LoadMetaHashIfNecessary()

**Comment by jeenfang** [comment]
public void Analyze()
        {
            if (_isAnalyzed) return;
            _isAnalyzed = true;

#if !UNITY_5
            LoadMetaHashIfNecessary();
#endif

**Comment by tangzx** [comment]
之前的unity4需要处理这个，监视一些资源的变动情况，Unity5之后不用了。总之这个是遗留代码不用管了
