### ISSUE TITLE
安卓下Stripping Level 如果选择StripAssemblies, HashUtils Error

### ISSUE THREAD

**Issue by 3wz** [tangzx/ABSystem#6]
我发现如果再Build Setting里设置代码剥离级别为 Strip Assemblies时候, 所提供的的HashUtils里面的
HashAlgorithm.Create()方法返回的实例为null, 并且我单独只用这个脚本建立demo尝试过, 最后谷歌了一下, 发现需要添加link.xml文件, 并且需要里面添加指定不被剥离命名空间才可以, 请问作者没有遇到这个问题吗?
建议在git库里把link.xml添加进去.
具体link.xml内容如下: 试了这个才好使
`<linker>
  <assembly fullname="System.Core">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
  <assembly fullname="mscorlib">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
  <assembly fullname="System">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
  <assembly fullname="System.Security">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
  <assembly fullname="Mono.Security">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
</linker>`

**Comment by tangzx** [comment]
好主意，已添加
