### ISSUE TITLE
打包面板Asset Filter条目过多时就看不见了, 希望加上滚动条

### ISSUE THREAD

**Issue by 3wz** [tangzx/ABSystem#7]
就是那个条目变多时候, 突然才意识到这个问题, 然后我尝试把条目增加很多, 然后也超过最大化的窗口时, 下面的过滤条目就看不到了, 然后也没滚动条, 然后我就给加了个, `希望您顺手加上~~
代码如下:

**Vector2 scollbarPos = Vector2.zero;**
GUILayout.BeginVertical();
**scollbarPos = GUILayout.BeginScrollView(scollbarPos, "HiddenScrollbar", "verticalscrollbar");
GUILayout.EndScrollView();**
GUILayout.EndVertical();

scollbarPos是字段, 然后在那个//context后的开始竖向布局和结束布局加上那两句代码就成.

**Comment by tangzx** [comment]
已加 :+1:
