### ISSUE TITLE
不好意思, 之前提供的link.xml过滤内容有问题

### ISSUE THREAD

**Issue by 3wz** [tangzx/ABSystem#9]
`<linker>
  <assembly fullname="mscorlib">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
</linker>`

我今天发现 如果选择.NET 2.0 Subset 将导致IL2CPPBuild失败, 如果是选Mono或者选.Net 2.0 编译则没有问题,  查找了下原因, 原来是link.xml的问题, 然后我尝试去掉一些, 最后发现只留这一个就可以了, 而且也能顺利通过Build. 抱歉之前有些不严谨了.

**Comment by tangzx** [comment]
已更新 :+1:
